name: API EXP

on:
  # push:
  #   branches: ["master", "develop"]
  # pull_request:
  #   types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Generate Prisma Client
        run: yarn generate

      - name: Build API
        run: yarn build:api

      - name: Create API build directory
        run: cp -r dist/apps/api build

      - name: Copy database library
        run: cp -r libs/database/prisma build/prisma

      - name: Generate environment variables
        run: |
          cd build
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL_EXP }} >> .env

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build
      #     path: build

      - name: Stop current application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd /home/deployer/api/
            pm2 stop API || true

      - name: Upload files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          TARGET: "/home/deployer/api"

      - name: Install remote packages and generate prisma client
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd /home/deployer/api/
            yarn
            npx prisma generate

      - name: Force push database schema
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd /home/deployer/api/
            npx prisma db push --accept-data-loss --force-reset

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd /home/deployer/api/
            pm2 start main.js --name API
