name: API DEV

on:
  # push:
  #   branches: ["master", "develop"]
  # pull_request:
  #   types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: "yarn"

      - name: Upload files (TEST)
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SOURCE: "apps/api"
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          TARGET: "/home/deployer/api"

      # - name: Install dependencies
      #   run: yarn

      # - name: Generate Prisma Client
      #   run: yarn generate

      # - name: Build API
      #   run: yarn build:api

      # - name: Create API build directory
      #   run: cp -r dist/apps/api build

      # - name: Copy database library
      #   run: cp -r libs/database/prisma build/prisma

      # - name: Generate environment variables
      #   run: |
      #     cd build
      #     touch .env
      #     echo DATABASE_URL="test" >> .env

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build
      #     path: build
