name: API DEV

on:
  # push:
  #   branches: ["master", "develop"]
  # pull_request:
  #   types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build API
        run: yarn build:api

      - name: Create API build directory
        run: cp dist/api build

      - name: List directory
        run: |
          cd build
          ls -la

      - name: Copy database library
        run: cp libs/database/prisma build/prisma

      - name: List directory
        run: |
          pwd
          ls -la

      - name: Generate environment variables
        run: |
          touch .env
          echo DATABASE_URL="test"

      - name: Generate prisma client
        run: npx prisma generate

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
