name: API Experiemental

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Generate Prisma Client
        run: yarn db:generate

      - name: Build API
        run: yarn build:api

      - name: Create API build directory
        run: cp -r dist/apps/api build

      - name: Copy database library
        run: cp -r libs/database/prisma build/prisma

      - name: Generate environment variables
        run: |
          cd build
          touch .env
          echo DATABASE_URL=${{ vars.DATABASE_URL_EXP }} >> .env
          echo JWT_SECRET=${{ vars.JWT_SECRET_EXP }} >> .env
          echo TOKEN_EXPIRY=${{ vars.TOKEN_EXPIRY_EXP }} >> .env

          echo BRANCH=EXPERIMENTAL >> .env
          echo API_PORT=5002 >> .env

      - name: Stop current application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST_DEV_EXP }}
          username: ${{ vars.DEPLOY_USER_DEV_EXP }}
          password: ${{ vars.DEPLOY_PASSWORD_DEV_EXP }}
          port: ${{ vars.DEPLOY_PORT_DEV_EXP }}
          script: |
            cd /home/deployer/exp/api/
            pm2 stop API-Exp || true

      - name: Upload files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ vars.DEPLOY_KEY_DEV_EXP }}
          SOURCE: "build/"
          REMOTE_HOST: ${{ vars.DEPLOY_HOST_DEV_EXP }}
          REMOTE_USER: ${{ vars.DEPLOY_USER_DEV_EXP }}
          REMOTE_PORT: ${{ vars.DEPLOY_PORT_DEV_EXP }}
          TARGET: "/home/deployer/exp/api"

      - name: Install remote packages and generate prisma client
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST_DEV_EXP }}
          username: ${{ vars.DEPLOY_USER_DEV_EXP }}
          password: ${{ vars.DEPLOY_PASSWORD_DEV_EXP }}
          port: ${{ vars.DEPLOY_PORT_DEV_EXP }}
          script: |
            cd /home/deployer/exp/api/
            yarn
            npx prisma generate

      - name: Force push database schema
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST_DEV_EXP }}
          username: ${{ vars.DEPLOY_USER_DEV_EXP }}
          password: ${{ vars.DEPLOY_PASSWORD_DEV_EXP }}
          port: ${{ vars.DEPLOY_PORT_DEV_EXP }}
          script: |
            cd /home/deployer/exp/api/
            npx prisma db push --accept-data-loss

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST_DEV_EXP }}
          username: ${{ vars.DEPLOY_USER_DEV_EXP }}
          password: ${{ vars.DEPLOY_PASSWORD_DEV_EXP }}
          port: ${{ vars.DEPLOY_PORT_DEV_EXP }}
          script: |
            cd /home/deployer/exp/api/
            pm2 start main.js --name API-Exp
