name: WEB Develop

on:
  workflow_dispatch:
    branches: ["develop"]

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: "yarn"

      - name: Generate environment variables
        run: |
          touch .env
          echo NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL_DEV }} >> .env

      - name: Install dependencies
        run: yarn

      - name: Generate Prisma Client
        run: yarn db:generate

      - name: Build WEB
        run: yarn build:web

      - name: Create WEB build directory
        run: cp -r dist/apps/web build

      - name: Stop current application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST_DEV }}
          username: ${{ vars.DEPLOY_USER_DEV }}
          password: ${{ vars.DEPLOY_PASSWORD_DEV }}
          port: ${{ vars.DEPLOY_PORT_DEV }}
          script: |
            cd /home/deployer/dev/web/
            pm2 delete WEB-Dev || true

      - name: Upload files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ vars.DEPLOY_KEY_DEV }}
          SOURCE: "build/"
          REMOTE_HOST: ${{ vars.DEPLOY_HOST_DEV }}
          REMOTE_USER: ${{ vars.DEPLOY_USER_DEV }}
          REMOTE_PORT: ${{ vars.DEPLOY_PORT_DEV }}
          TARGET: "/home/deployer/dev/web"

      - name: Install remote packages
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST_DEV }}
          username: ${{ vars.DEPLOY_USER_DEV }}
          password: ${{ vars.DEPLOY_PASSWORD_DEV }}
          port: ${{ vars.DEPLOY_PORT_DEV }}
          script: |
            cd /home/deployer/dev/web/
            yarn

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST_DEV }}
          username: ${{ vars.DEPLOY_USER_DEV }}
          password: ${{ vars.DEPLOY_PASSWORD_DEV }}
          port: ${{ vars.DEPLOY_PORT_DEV }}
          script: |
            cd /home/deployer/dev/web/
            pm2 start yarn --name WEB-Dev -- start -p 3001
